# Generated by Django 5.1.1 on 2024-10-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbgroup",
            name="likes_count",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
