# Generated by Django 5.1.1 on 2024-10-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fb", "0002_fbgroup_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbgroup",
            name="followers_count",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
